### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by arteymix** [valum-framework/vsgi#1]
Here's a list of feature and target we should aim for a `1.0` release:

 - [ ] portable and Windows support
 - [ ] clustering via `GLib.Subprocess` and file descriptor sharing
 - [ ] stable server API/ABI

The main issue with `fork` is portability. While it works great on UNIX, it's not applicable on other platforms. The alternate strategy would be to use spawn (fork + exec with Windows-specific fallback), inherit file descriptors and set the child server to listen to them. Given it being a proper `GLib.Subprocess`, communication via pipe would be built-in.

**Comment by arteymix** [comment]
Given the timing of this release, I think we should look into porting VSGI to [libsoup 3](https://libsoup.org/libsoup-3.0/index.html). There's some interesting benefits including usage of actual GInputStream and GOutputStream APIs which would get write of the Soup.Message wrappers.
